---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: postgis
    image: postgis/postgis
    ports:
    - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: docker
      - name: POSTGRES_DB
        value: cas
  - name: frontend
    image: nome_utente/nome_immagine_frontend:cas
    ports:
    - containerPort: 8001
  - name: backend
    image: nome_utente/nome_immagine_backend:cas
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    name: my-pod
  ports:
  - name: frontend-port
    port: 8001
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    name: my-pod
  ports:
  - name: backend-port
    port: 8000
    targetPort: 8000
